pfc_app/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.cursos, name='home'),
    path('accounts/login/', views.login, name='login'),
    path('registrar/', views.registrar, name='registrar'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('cursos/', views.cursos, name='lista_cursos'),
    path('ch/', views.carga_horaria, name='carga_horaria'),
    path('inscricoes/', views.inscricoes, name='inscricoes'),
    path('curso_detail/<int:pk>', views.CursoDetailView.as_view(), name='detail_curso'),
    path('curso_detail/<int:pk>/<str:lotado>', views.CursoDetailView.as_view(), name='detail_curso'),
    path('sucesso_inscricao/', views.sucesso_inscricao, name='sucesso_inscricao'),
    path('inscricao_existente/', views.inscricao_existente, name='inscricao_existente'),
    path('inscrever/<int:curso_id>/', views.inscrever, name='inscrever_curso'),
    path('avaliacao/<int:curso_id>/', views.avaliacao, name='avaliacao'),
    path('inscricao_cancelar/<int:inscricao_id>/', views.cancelar_inscricao, name='cancelar_inscricao'),
    path('validar_ch/', views.validar_ch, name='validar_ch'),
    path('download_all_pdfs/', views.download_all_pdfs, name='download_all_pdfs'),
    path('generate_all_pdfs/<int:curso_id>/', views.generate_all_pdfs, name='generate_all_pdfs'),
    path('generate_all_pdfs/<int:curso_id>/<int:unico>/', views.generate_all_pdfs, name='generate_all_pdfs'),
    path('generate_single_pdf/<int:inscricao_id>/', views.generate_single_pdf, name='generate_single_pdf'),
    path('reset-password/', views.reset_password_request, name='reset_password_request'),
    path('change-password/', views.change_password, name='change_password'),
    path('generate_reconhecimento/<int:validacao_id>/', views.generate_all_reconhecimento, name='generate_reconhecimento'),
    path('gerar_ata/<int:curso_id>/', views.gerar_ata, name='gerar_ata'),
    path('gerar_relatorio/<int:curso_id>/', views.gerar_relatorio, name='gerar_relatorio'),
    path('relatorio/', views.relatorio, name='relatorio'),
    path('explorer/', include('explorer.urls')),
    path('usuarios_sem_ch/', views.usuarios_sem_ch, name='usuarios_sem_ch'),
    path('gerar_curadoria/<int:ano>/<int:mes>', views.gerar_curadoria, name='gerar_curadoria'),
    path('curadoria/', views.curadoria, name='curadoria'),
    path('curadoria_show/', views.curadoria_html_show, name='curadoria_show'),
    path('curadoria_html/<int:ano>/<int:mes>/', views.curadoria_html, name='curadoria_html'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pfc_app_django/urls.py
from django.contrib import admin
from django.urls import path, include
from pfc_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pfc_app.urls')),
]

pfc_app/models.py
from django.db import models
from django import forms
import os
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_save
from django.dispatch import receiver
import base64
from django.conf import settings
from django.utils import timezone

# Create your models here.

class User(AbstractUser):
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    cpf = models.CharField(max_length=11, blank=False, null=False, unique=True)
    nome = models.CharField(max_length=400, blank=False, null=False)
    email = models.EmailField(default='a@b.com', null=False, blank=False, unique=True)
    telefone = models.CharField(max_length=40, blank=True, null=True)
    cargo = models.CharField(max_length=400, blank=True, null=True)
    nome_cargo = models.CharField(max_length=400, blank=True, null=True)
    categoria = models.CharField(max_length=400, blank=True, null=True)
    grupo_ocupacional = models.CharField(max_length=400, blank=True, null=True)
    origem = models.CharField(max_length=400, blank=True, null=True)
    simbologia = models.CharField(max_length=400, blank=True, null=True)
    tipo_atuacao = models.CharField(max_length=400, blank=True, null=True)
    lotacao = models.CharField(max_length=400, blank=True, null=True)
    lotacao_especifica = models.CharField(max_length=400, blank=True, null=True)
    lotacao_especifica_2 = models.CharField(max_length=400, blank=True, null=True, verbose_name = ("Lotação sigla"))
    classificacao_lotacao = models.CharField(max_length=400, blank=True, null=True)

    is_ativo = models.BooleanField(default=True)
    role = models.CharField(max_length=40, default="USER")
    is_externo = models.BooleanField(default=False, verbose_name = ("É externo"))
    avatar = models.ImageField(null=True, blank=True)
    avatar_base64 = models.TextField(blank=True, null=True)
    
    USERNAME_FIELD = "cpf"

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        self.nome = self.nome.upper()
        self.first_name = self.first_name.upper()
        self.last_name = self.last_name.upper()
        if self.avatar:
            # Leia a imagem em bytes
            image_data = self.avatar.read()
            # Converta a imagem em base64
            base64_data = base64.b64encode(image_data).decode('utf-8')
            # Salve a imagem em base64 no campo avatar_base64
            self.avatar_base64 = base64_data

        self.avatar = None
        super(User, self).save(*args, **kwargs)

        if self.avatar:
            os.remove(self.avatar.path)

            # Defina o campo avatar como vazio para garantir que o arquivo não seja salvo novamente
            


class StatusCurso(models.Model):
    nome = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nome

class StatusInscricao(models.Model):
    nome = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "status inscrições"
    

class Competencia(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)

    def __str__(self):
        return self.nome
    

class Trilha(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)
    ativa = models.BooleanField(default=True, verbose_name = ("Está ativa"))
    competencias = models.ManyToManyField(Competencia)
    cor_circulo = models.CharField(max_length=7, default='#000000')
    ordem_relatorio = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name = ("Ordem no relatório"))
    fundo_tabela = models.CharField(max_length=7, default='#F3F3F3')

    def __str__(self):
        return self.nome

class InstituicaoPromotora(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)
    def __str__(self):
        return self.nome


class InstituicaoCertificadora(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)
    def __str__(self):
        return self.nome

class Categoria(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)
    def __str__(self):
        return self.nome
    
class Modalidade(models.Model):
    nome = models.CharField(max_length=400, blank=False, null=False)
    def __str__(self):
        return self.nome

class Curso(models.Model):
    TURNO_CHOICES = [
        ('MANHA', 'MANHÃ'),
        ('TARDE', 'TARDE'),
        ('NOITE', 'NOITE'),
    ]
    TURMA_CHOICES = [
        ('TURMA1', 'TURMA 1'),
        ('TURMA2', 'TURMA 2'),
        ('TURMA3', 'TURMA 3'),
        ('TURMA4', 'TURMA 4'),
        ('TURMA5', 'TURMA 5'),
    ]

    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    nome_curso =  models.CharField(max_length=400, blank=False, null=False)
    ementa_curso =  models.TextField(max_length=4000, blank=False, null=False)
    modalidade = models.ForeignKey(Modalidade, on_delete=models.SET_NULL, blank=True, null=True)
    tipo_reconhecimento = models.CharField(max_length=400, blank=True, null=True)
    ch_curso = models.IntegerField(blank=False, null=False)
    vagas = models.IntegerField(blank=False, null=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, blank=True, null=True)
    descricao = models.TextField(max_length=4000, default='')
    data_inicio = models.DateField(blank=False, null=False)
    data_termino = models.DateField(blank=True, null=True)
    turno = models.CharField(max_length=10, choices=TURNO_CHOICES, default="TARDE")
    turma = models.CharField(max_length=10, choices=TURMA_CHOICES, default="TURMA1")
    inst_certificadora = models.ForeignKey(InstituicaoCertificadora, on_delete=models.SET_NULL, blank=True, null=True)
    inst_promotora = models.ForeignKey(InstituicaoPromotora, on_delete=models.SET_NULL, blank=True, null=True)
    participantes = models.ManyToManyField(User, through='Inscricao', related_name='curso_participante')
    avaliacoes = models.ManyToManyField(User, through='Avaliacao', related_name='curso_avaliacao')
    #acao = models.ForeignKey(Acao, on_delete=models.CASCADE)
    #gestor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    coordenador = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    #history = HistoricalRecords()
    status = models.ForeignKey(StatusCurso, on_delete=models.PROTECT)
    trilha = models.ForeignKey(Trilha, on_delete=models.PROTECT, blank=True, null=True, related_name='cursos')
    periodo_avaliativo = models.BooleanField(default=False)
    eh_evento = models.BooleanField(default=False, verbose_name = ("É evento"))
    observacao = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Observação"))
    horario = models.TextField(max_length=400, blank=True, null=True, verbose_name = ("Horário"))

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.nome_curso
    


class PlanoCurso(models.Model):
    curso = models.OneToOneField(Curso, on_delete=models.CASCADE) 
    publico_alvo = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Público-alvo"))
    quantidade_turma = models.SmallIntegerField(blank=True, null=True, verbose_name = ("Quantidade de turmas"))
    pre_requisitos = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Pré-requisitos"))
    objetivo_geral = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Objetivo geral"))
    objetivo_especifico = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Objetivo específico"))
    metodologia_ensino = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Metodologia de ensino"))
    metodologia_avaliacao = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Metodologia de avaliação"))
    recursos_professor = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Recursos professor"))
    recursos_aluno = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Recursos aluno"))
    referencia_bibliografica = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Referências bibliográficas"))
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return 'Plano do curso: ' + self.curso.nome_curso
    
    class Meta:
        verbose_name_plural = "planos de curso"
        verbose_name = "plano de curso"

class CronogramaExecucao(models.Model):
    TURNO = [
        ('MANHÃ', 'MANHÃ'),
        ('TARDE', 'TARDE'),
    ]
    plano = models.ForeignKey(PlanoCurso, on_delete=models.CASCADE) 
    aula = models.SmallIntegerField(blank=True, null=True)
    turno = models.CharField(max_length=10, choices=TURNO, blank=True, null=True)
    conteudo = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Conteúdo"))
    atividade = models.TextField(max_length=4000, blank=True, null=True, verbose_name = ("Atividades"))

    class Meta:
        verbose_name_plural = "cronogramas de execução"

class Inscricao(models.Model):
    CONDICAO_ACAO_CHOICES = [
        ('DISCENTE', 'DISCENTE'),
        ('DOCENTE', 'DOCENTE'),
    ]
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    participante = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = ("Usuário"))
    ch_valida = models.IntegerField(blank=True, null=True)
    condicao_na_acao = models.CharField(max_length=400, choices=CONDICAO_ACAO_CHOICES, blank=False, null=False, default="DISCENTE")
    status = models.ForeignKey(StatusInscricao, on_delete=models.PROTECT)
    concluido = models.BooleanField(default=False)

pfc_app/forms.py
from django import forms
from .models import Avaliacao, Subtema, User  # Certifique-se de importar o modelo Avaliacao
from django.forms import FileInput


CHOICES=[('1','1'),
         ('2','2'),
         ('3','3'),
         ('4','4'),
         ('5','5'),
         ('0','N/A'),
         ]
class AvaliacaoForm(forms.ModelForm):
    
    class Meta:
        model = Avaliacao
        fields = '__all__'  # Use todos os campos do modelo Avaliacao
        # widgets = {
        #     'nota_atributo1': forms.RadioSelect(),
        #     'nota_atributo2': forms.RadioSelect(),
        #     'nota_atributo3': forms.RadioSelect(),
        #     'nota_atributo4': forms.RadioSelect(),
        #     'nota_atributo5': forms.RadioSelect()
        # }
        #choices=CHOICES
        exclude = ['curso', 'participante']

    def __init__(self, *args, **kwargs):
        super(AvaliacaoForm, self).__init__(*args, **kwargs)

        # Personalize os widgets para usar classes do Bootstrap
        #for field_name, field in self.fields.items():
         #   field.widget.attrs['class'] = 'form-control'

class DateFilterForm(forms.Form):
    data_inicio = forms.DateField(label='Data de Início', required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    data_fim = forms.DateField(label='Data de Fim', required=False, widget=forms.TextInput(attrs={'type': 'date'}))

class SubtemaForm(forms.ModelForm):
    class Meta:
        model = Subtema
        fields = ['nome', 'tema', 'cor']  # Inclui apenas o campo que você deseja modificar
        widgets = {
            'cor': forms.TextInput(attrs={'type': 'color'}),
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'telefone', 'avatar']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        }

    telefone = forms.CharField(required=False, max_length=40, label='Telefone')

pfc_app/templates/pfc_app/agenda_pfc.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}

    <div class="d-flex p-2 justify-content-center mb-2"><h1>AGENDA PFC DE {{mes_escolhido}}</h1></div>
    {% for trilha, dados in trilhas_com_cursos.items %}
        <div class="d-flex align-items-center mb-2">
            <div style="width: 30px; height: 30px; border-radius: 50%; background-color: {{ dados.cor_circulo }}; margin-right: 10px;"></div>
            <h2 style="color: {{ dados.cor_circulo }}">{{ trilha.nome }}</h2>
        </div>
        <div class="content pb-5">
        {% if dados.curadorias %}
        <table style="width: 100%; border-collapse: collapse; border: 2px solid white;">
            <tr style="background-color: {{ dados.cor_circulo }};">
                <th style="width: 55%; border: 2px solid white; color: white; text-align: center;">Curadoria</th>
                <th style="width: 10%; border: 2px solid white; color: white; text-align: center;">Link</th>
                <th style="width: 5%; border: 2px solid white; color: white; text-align: center;">CH</th>
                <th style="width: 10%; border: 2px solid white; color: white; text-align: center;">Modalidade</th>
                <th style="width: 20%; border: 2px solid white; color: white; text-align: center;">Promotor</th>
            </tr>
            {% for curadoria in dados.curadorias %}
            <tr style="background-color: {{ dados.fundo_tabela }};">
                <td style="border: 2px solid white; text-align: center;">{{ curadoria.nome_curso }}</td>
                <td style="border: 2px solid white; text-align: center;"><a href="{{ curadoria.link_inscricao }}">Inscrição</a></td>
                <td style="border: 2px solid white; text-align: center;">{{ curadoria.carga_horaria_total }}</td>
                <td style="border: 2px solid white; text-align: center;">{{ curadoria.modalidade.nome }}</td>
                {% if curadoria.instituicao_promotora %}
                    <td style="border: 2px solid white; text-align: center;">{{ curadoria.instituicao_promotora.nome }}</td>
                {% else %}
                    <td style="border: 2px solid white; text-align: center;">{{ '' }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        {% endif %}

        {% if dados.cursos %}
        <table style="width: 100%; border-collapse: collapse; border: 2px solid white;">
            <tr style="background-color: {{ dados.cor_circulo }};">
                <th style="width: 55%; border: 2px solid white; color: white; text-align: center;">PFC</th>
                <th style="width: 10%; border: 2px solid white; color: white; text-align: center;">Link</th>
                <th style="width: 5%; border: 2px solid white; color: white; text-align: center;">CH</th>
                <th style="width: 10%; border: 2px solid white; color: white; text-align: center;">Modalidade</th>
                <th style="width: 20%; border: 2px solid white; color: white; text-align: center;">Período</th>
            </tr>
            {% for curso in dados.cursos %}
            <tr style="background-color: {{ dados.fundo_tabela }};">
                <td style="border: 2px solid white; text-align: center;">{{ curso.nome_curso }}</td>
                <td style="border: 2px solid white; text-align: center;"><a href="https://www.pfc.seplag.pe.gov.br/curso_detail/{{ curso.id }}">Inscrição</a></td>
                <td style="border: 2px solid white; text-align: center;">{{ curso.ch_curso }}</td>
                <td style="border: 2px solid white; text-align: center;">{{ curso.modalidade.nome }}</td>
                <td style="border: 2px solid white; text-align: center;">de {{ curso.data_inicio|date:"d/m/Y" }} a {{ curso.data_termino|date:"d/m/Y" }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        </div>
    {% endfor %}
{% endblock %}

pfc_app/templates/pfc_app/curadoria_show.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}

<div class="d-flex p-2 justify-content-center mb-0"><h1>VISUALIZAR AGENDA PFC</h1></div>

        <form method="POST" class="mt-3" enctype="multipart/form-data">
            {% csrf_token %}
                
                <div class="row mb-3">
                  <div class="col-md-8 col-sm-12 text-md-start text-center">
                      
                    <div class=" form-floating mb-3">
                        <select class="form-control" style="background-color: #f5f5f5;" name="ano" id="id_ano">
                            {% for ano in anos %}
                                <option value="{{ ano }}">{{ ano }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_categoria">Escolha o ano</label>
                    </div>
                    <div class=" form-floating mb-3">
                        <select class="form-control" style="background-color: #f5f5f5;" name="mes" id="id_mes">
                            {% for code, name in meses %}
                            <option value="{{ code }}">{{ name }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_categoria">Escolha o mês</label>
                    </div>
                  </div>
                </div>
               
            
            
            <button type="submit" class="btn btn-primary">Visualizar Agenda</button>
        </form>

{% endblock %}

pfc_app/templates/pfc_app/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'parciais/_messages.html' %}


<div class="container d-flex justify-content-center bg-gradient pt-3" 
        style="background-color: rgb(112,44,249); height: 20vh; margin-bottom: -5vh;">
    <h1 style="color: #fdfdfd">Dashboard</h1>
</div>

<div class="container">
    <div class="row d-flex justify-content-between align-items-start">

        <div class="col-md-3  col-12  border rounded zoom my-2" 
            style="height: 15vh; background-color: rgb(250,250,250, 0.8);">
            <div class="row d-flex justify-content-center align-items-center" style="height:100%;">
                <img class="img-fluid " src="{% static 'naruto.png' %}" alt="" style="height: 100%; width: auto;">
                <div class="col"><h5>240 horas-aula entregues</h5></div>
            </div>    
        </div>
        <div class="col-md-3  col-12  border rounded zoom my-2" 
            style="height: 15vh; background-color: rgb(250,250,250, 0.8);">
            <div class="row d-flex justify-content-center align-items-center" style="height:100%;">
                <img class="img-fluid " src="{% static 'nerd-diploma.png' %}" alt="" 
                    style="height: 100%; width: auto;">
                <div class="col"><h5>40 inscrições concluídas</h5></div>
            </div>    
        </div>
        <div class="col-md-3  col-12  border rounded zoom my-2" 
            style="height: 15vh; background-color: rgb(250,250,250, 0.8);">
            <div class="row d-flex justify-content-center align-items-center" style="height:100%;">
                <img class="img-fluid " src="{% static 'quadro.png' %}" alt="" style="height: 100%; width: auto;">
                <div class="col"><h5>10 cursos ministrados</h5></div>
            </div>    
        </div>
        
    </div>
</div>
{% endblock %}

pfc_app/templates/pfc_app/download_all_pdfs.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}

<h1>Download de Todos os PDFs</h1>
    <a href="{% url 'generate_all_pdfs' %}" class="btn btn-primary">Baixar Todos os PDFs</a>

{% endblock %}

pfc_app/templates/pfc_app/enviar_pdf.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}

<div class="d-flex p-2 justify-content-center mb-5"><h1>VALIDAR CURSO EXTERNO</h1></div>
<div class="d-flex row">
    <div class="col-md-5 col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="col form-floating mb-3">
                <input type="input" class="form-control" name="nome_curso" id="nome_curso_id" required>
                <label for="nome_curso_id" >Nome do Curso Para Validação</label>
            </div>
            <div class="col form-floating mb-3">
                <input type="input" class="form-control" name="ch_solicitada" id="ch_solicitada_id" required>
                <label for="ch_solicitada_id" >Carga Horária Solicitada</label>
            </div>
            <div class="col form-floating mb-3">
                <input type="date" class="form-control" name="data_inicio"  id="id_data_inicio" required>
                <label for="id_data_inicio" >Data de Início do Curso</label>
            </div>
            <div class="col form-floating mb-3">
                <input type="date" class="form-control" name="data_termino"  id="id_data_termino" required>
                <label for="id_data_termino" >Data de Término do Curso</label>
            </div>
            <div class="col form-floating mb-3">
                <input type="input" class="form-control" name="instituicao_promotora" id="instituicao_promotora_id" required>
                <label for="instituicao_promotora_id" >Instituição Promotora</label>
            </div>
            <div class="col form-floating mb-3">
                <textarea class="form-control" name="ementa" id="ementa_id" rows="4"  required></textarea>
                <label for="ementa_id" >Ementa</label>
            </div>
            <div class="col  mb-3 form-check">
                <input class="form-check-input" type="checkbox" value="sim" id="agenda_pfc_id" name="agenda_pfc">
                <label class="form-check-label" for="agenda_pfc_id">
                    Ficou sabendo pela agenda PFC?
                </label>
            </div>
            <div class="input-group input-group-md mb-3 mr-3 mt-3">
                <div class="col input-group-md">
                    <input type="file" class="form-control" id="inputGroupFile02" name="arquivo_pdf" accept=".pdf" title="Escolha um Arquivo" required>
                </div>
                <button class="input-group-text btn-primary" for="inputGroupFile02" type="submit">Enviar</button>
                
            </div>
        </form>
    </div>
    <div class="col-md-7 col-12 px-3 overflow-auto border rounded" style="height: 60vh;">
        <div class="d-flex p-2 justify-content-center mb-5"><h3>Minhas Validações</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Nome do curso</th>
                <th scope="col">Instituição promotora</th>
                <th scope="col">Carga horária solicitada</th>
                <th scope="col">Carga horária validada</th>
                <th scope="col">Situação</th>
              </tr>
            </thead>
            <tbody>
            {% for validacao in validacoes %}
              <tr>
                <th scope="row">{{ validacao.nome_curso }}</th>
                <td>{{ validacao.instituicao_promotora }}</td>
                <td>{{ validacao.ch_solicitada }}</td>
                <td>{{ validacao.ch_confirmada }}</td>
                <td>{{ validacao.status }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
</div>
{% endblock %}

pfc_app/templates/pfc_app/presentation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'parciais/_messages.html' %}
<div class="d-flex w-100 justify-content-center mt-3">
<div class=" col-md-3 col-12">
 
        <img class="mb-1 mx-auto d-block" src="{% static 'pfc_app/logos/Logo2024-180x180.png' %}" alt="" width="auto" height="150">
        <h1 class="h1 mb-3 fw-normal text-center">TÁ CHEGANDO O DIA!!!</h1>

        
</div>
</div>



{% endblock %}

pfc_app/templates/pfc_app/relatorio.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}

<div class="d-flex p-2 justify-content-center mb-0"><h1>GERAR RELATÓRIO</h1></div>

        <form method="POST" class="mt-3" enctype="multipart/form-data">
            {% csrf_token %}
                
                <div class="row mb-3">
                  <div class="col-md-8 col-sm-12 text-md-start text-center">
                      
                    <div class=" form-floating mb-3">
                        <select class="form-control" style="background-color: #f5f5f5;" name="curso" id="id_curso">
                            {% for curso in cursos %}
                                <option value="{{ curso.id }}">{{ curso.nome_curso }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_categoria">Escolha o curso</label>
                    </div>
                    <div class="form-group">
                        <label for="id_fotos">Selecionar Fotos:</label>
                        <input type="file" class="form-control-file" id="id_fotos" name="fotos" multiple>
                    </div>
                  </div>
                </div>
               
            
            
            <button type="submit" class="btn btn-primary m-2">Gerar Relatório</button>
        </form>

{% endblock %}

pfc_app/templates/pfc_app/reset_password_request.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-5">
<form method="post">
    {% include 'parciais/_messages.html' %}
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Digite seu email cadastrado</h1>
      <label for="email" class="sr-only">Email</label>
      <input type="email" name="email" id="id_email" class="form-control" placeholder="email" required autofocus>
    <button class="btn btn-md btn-primary btn-block mt-3 mb-3" type="submit">Enviar Nova Senha</button>
</form>
</div>
<div class="col"></div>
</div>
{% endblock %}

pfc_app/templates/pfc_app/sucesso_inscricao.html
{% extends 'base.html' %}

{% block content %}
{% include 'parciais/_messages.html' %}
boa! consegui
{% endblock %}